'use client'

import { useEffect, useState } from 'react'
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card'
import { Button } from '@/components/ui/button'
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from '@/components/ui/table'
import { FileText, FileType, Sheet, Download, Trash2, Clock, CheckCircle, Loader2 } from 'lucide-react'
import { Badge } from '@/components/ui/badge'

export function ReportHistory({ projectId, isAdmin }: { projectId: string, isAdmin: boolean }) {
  const [reports, setReports] = useState<any[]>([])
  const [loading, setLoading] = useState(true)

  useEffect(() => {
    fetchReports()
    
    // Poll every 3 seconds if any report is "Generating"
    const interval = setInterval(() => {
      setReports((currentReports) => {
        if (currentReports.some(r => r.status === "Generating")) {
          fetchReports(false);
        }
        return currentReports;
      });
    }, 3000);

    return () => clearInterval(interval);
  }, [])

  const fetchReports = async (showLoading = true) => {
    if (showLoading) setLoading(true)
    try {
      const res = await fetch(`/api/projects/${projectId}/reports`)
      if (res.ok) {
        const data = await res.json()
        setReports(data)
      }
    } catch (error) {
      console.error(error)
    } finally {
      if (showLoading) setLoading(false)
    }
  }

  const deleteReport = async (id: string) => {
    if (!confirm('Are you sure you want to delete this report?')) return

    try {
      const res = await fetch(`/api/reports/${id}`, { method: 'DELETE' })
      if (res.ok) {
        setReports(reports.filter(r => r.id !== id))
      }
    } catch (error) {
      console.error(error)
    }
  }

  const downloadReport = (id: string, filename: string) => {
    window.open(`/api/reports/${id}/download`, '_blank')
  }

  return (
    <Card className="border-border/50 shadow-sm overflow-hidden mt-6">
      <CardHeader className="border-b border-border/50 bg-muted/20 pb-4">
        <CardTitle className="text-xl flex items-center gap-2">
          <Clock className="h-5 w-5 text-primary" />
          Report History
        </CardTitle>
        <CardDescription>
          A complete history of all generated reports for this assessment.
        </CardDescription>
      </CardHeader>
      <CardContent className="p-0">
        {loading ? (
          <div className="p-8 text-center text-muted-foreground">Loading reports...</div>
        ) : reports.length === 0 ? (
          <div className="p-8 text-center text-muted-foreground">
            <CheckCircle className="h-10 w-10 mx-auto text-muted mb-4" />
            No reports have been generated yet.
          </div>
        ) : (
          <Table>
            <TableHeader className="bg-muted/30">
              <TableRow>
                <TableHead className="w-[100px]">Format</TableHead>
                <TableHead>Version</TableHead>
                <TableHead>Status</TableHead>
                <TableHead>Generated By</TableHead>
                <TableHead>Generated At</TableHead>
                <TableHead className="text-right">Actions</TableHead>
              </TableRow>
            </TableHeader>
            <TableBody>
              {reports.map((report) => (
                <TableRow key={report.id}>
                  <TableCell className="font-medium">
                    <div className="flex items-center gap-2">
                      {report.format === 'PDF' && <FileText className="h-4 w-4 text-red-500" />}
                      {report.format === 'DOCX' && <FileType className="h-4 w-4 text-blue-500" />}
                      {report.format === 'EXCEL' && <Sheet className="h-4 w-4 text-green-500" />}
                      {report.format}
                    </div>
                  </TableCell>
                  <TableCell>v{report.version}</TableCell>
                  <TableCell>
                    {report.status === "Generating" ? (
                      <Badge variant="outline" className="bg-blue-500/10 text-blue-500 border-blue-500/20">
                        <Loader2 className="mr-1 h-3 w-3 animate-spin" />
                        Generating
                      </Badge>
                    ) : report.status === "Failed" ? (
                      <Badge variant="outline" className="bg-red-500/10 text-red-500 border-red-500/20">Failed</Badge>
                    ) : (
                      <Badge variant="outline" className="bg-emerald-500/10 text-emerald-500 border-emerald-500/20">Ready</Badge>
                    )}
                  </TableCell>
                  <TableCell>{report.generatedBy?.name || 'Unknown'}</TableCell>
                  <TableCell>{new Date(report.createdAt).toLocaleString()}</TableCell>
                  <TableCell className="text-right space-x-2">
                    {report.status === 'Ready' && (
                      <Button variant="outline" size="sm" onClick={() => downloadReport(report.id, report.filePath)}>
                        <Download className="h-4 w-4 mr-2" /> Download
                      </Button>
                    )}
                    {isAdmin && (
                      <Button variant="ghost" size="sm" onClick={() => deleteReport(report.id)} className="text-red-500 hover:text-red-600 hover:bg-red-50" disabled={report.status === 'Generating'}>
                        <Trash2 className="h-4 w-4" />
                      </Button>
                    )}
                  </TableCell>
                </TableRow>
              ))}
            </TableBody>
          </Table>
        )}
      </CardContent>
    </Card>
  )
}
